[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
espaceTestnet = "https://evmtestnet.confluxrpc.com"
espace = "https://evm.confluxrpc.com"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
